version: 2
workflows:
  version: 2
  test:
    jobs:
      - py36
      - py37

jobs:
  py36: &test-template
    working_directory: ~/repo
    docker:
      - image: circleci/python:3.6.15

    steps:
      - checkout

      - restore_cache:
          keys: deps-{{ checksum "pyproject.toml" }}

      - run:
          name: Install test dependencies
          command: |
            poetry install
            poetry add codecov

      - save_cache:
          key: deps-{{ checksum "pyproject.toml" }}
          paths:
            - /home/circleci/.cache/pypoetry/virtualenvs

      - run:
          name: Linters
          command:
            SKIP=no-commit-to-branch poetry run pre-commit run -a -v

      - run:
          name: Run tests
          command:
            poetry run pytest

      - run:
          name: codecov
          command:
            poetry run codecov

  py37:
    <<: *test-template
    docker:
      - image: circleci/python:3.7.12
